# folder where the data is downloaded
data_root: ../scans/

splits: [nvs_sem_train, nvs_sem_val]

scene_ids: [8b5caf3398, 116456116b, 13c3e046d7, 0a184cf634, 578511c8a9, 21d970d8de]

# The following paths should be given relative to the DATA_ROOT/dslr/
# If not given, will use the default directory defined in ScannetppScene class

input_image_dir: resized_images
input_mask_dir: resized_anon_masks
input_transforms_path: nerfstudio/transforms.json

# All use the relative path to DATA_ROOT/dslr/
out_image_dir: undistorted_images
out_mask_dir: undistorted_anon_masks
out_transforms_path: nerfstudio/transforms_undistorted.json