# folder where the data is downloaded
data_root: ../scans/

camera_model: PINHOLE
# Set True to render depth for iphone frames
render_iphone: False
# Set True to render depth for dslr frames
render_dslr: True

# render RGB and Depth as defualt
### Set True to render normals
render_normals: True
### Set True to render semantics
render_semantics: False
semantic_classes: ../scans/metadata/semantic_classes.txt
render_semantics_dir: render_semantic-nyu40
mapping_file: ../scans/metadata/semantic_benchmark/map_benchmark.csv
labels_path: ../scans/metadata/nyu40.txt
palette_path: ../scans/metadata/nyu40_palette.txt
ignore_label: -100

splits: [nvs_sem_train, nvs_sem_val]

# Specify scene ids if you want to render depth for specific scenes
scene_ids: [8b5caf3398, 116456116b, 13c3e046d7, 0a184cf634, 578511c8a9, 21d970d8de]

# The near and far planes for the depth camera during rendering in meters.
near: 0.05
far: 20.0

# Output directory for the rendered depth images. If not given, the output will be saved to data folder in data_root
output_dir: ../scans/data/