data:
  data_root: ../scans/data/

# nyu40.txt, semantic_classes.txt
  labels_path: ../scans/metadata/nyu40.txt
  # for instance segmentation
  use_instances: true
  instance_labels_path: ../scans/metadata/instance_classes.txt

  ## save multiple labels per vertex/point? ##
  # multilabel:
  #   max_gt: 3
  #   multilabel_only: false

  mapping_file: ../scans/metadata/semantic_benchmark/map_benchmark.csv

  list_path: ../scans/semantics-nyu40/pth/pth_lis.txt

  ignore_label: -100

  sample_factor: 1.0

  transforms:
    # read the mesh 
    - add_mesh_vertices
    # map raw labels to benchmark classes
    - map_label_to_index
    # use segments info to get labels on the vertices, handle multilabels
    - get_labels_on_vertices
    # sample points on the mesh and transfer all vertex info to the points
    # - sample_points_on_mesh

# dir to save pth training data
out_dir: ../scans/semantics-nyu40/pth
