
# extract RGB frames
extract_rgb: true
# extract anonymization masks
extract_masks: true
# extract depth frames
extract_depth: true

# folder where the data is downloaded
data_root: ../scans

splits: [nvs_sem_train, nvs_sem_val]

scene_ids: [0d2ee665be, 3f15a9266d]